name: KingKits
main: com.faris.kingkits.KingKits
version: ${project.version}
description: Have battles with enemies using custom made kits!
author: KingFaris10
softdepend: [Vault]
api-version: 1.13
commands:
    kingkits:
      description: KingKits plugin command.
      usage: /<command> [<reload|config>]
      aliases: [kk]
    pvpkit:
      description: List all the kits or choose a PvP kit!
      usage: /<command> [<name>|<name> <player>]
    createkit:
      description: Create a PvP Kit ingame with all the items in your inventory!
      usage: /<command> <name> [<guiItem>]
    deletekit:
      description: Delete a(ll) PvP kit(s).
      usage: /<command> <*|name>
    renamekit:
      description: Rename a PvP kit.
      usage: /<command> <name> <newname>
    createukit:
      description: Create a personal user PvP Kit ingame with all the items in your inventory!
      usage: /<command> <name> [<guiItem>]
    deleteukit:
      description: Delete a user PvP kit.
      usage: /<command> <name>
    renameukit:
      description: Rename a user PvP kit.
      usage: /<command> <name> <newname>
    previewkit:
      description: Preview a kit, or make another player preview a kit.
      usage: /<command> <kit> [<player>]
    refill:
      description: Refill bowl(s).
      usage: /<command> [<all>]
      aliases: [soup]
